### ISSUE TITLE
installation fails on nixos

### ISSUE THREAD

**Issue by teto** [jgm/yst#50]
hi,

yst seems exactly like what I am looking for. I have tried installing it on 'unstable' nixos (nixos.org) with its packages generated directly from hackage. There seems to be a dependancy problem and I am not familiar with the haskell ecosystem yet (that's part of the goal). The problem might stem from nixos but I thought I would ask.
```
configureFlags: --verbose --prefix=/nix/store/plxh7v91lg1hfy11bbqfhlpqyjz6qqrp-yst-0.5.1.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --datadir=/nix/store/z2jydslfjgwp2k5abd00b21w0p78q9ja-yst-0.5.1.1-data/share/ghc-8.0.2 --docdir=/nix/store/5y64mwkd5ix2ysx79cxaksii77h6akap-yst-0.5.1.1-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-yst-0.5.1.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/plxh7v91lg1hfy11bbqfhlpqyjz6qqrp-yst-0.5.1.1/lib/ghc-8.0.2/yst-0.5.1.1 --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --ghc-option=-split-sections Configuring yst-0.5.1.1... 
Setup: Encountered missing dependencies: 
aeson >=0.7 && <0.12,  
pandoc >=1.10 && <1.18
```
In nixos, only "pandoc-1.19.2.4" is available (apart from reverting to an old version).
Multiple versions seem available for aeson but I am not sure which one it chose as a dependency.
```
haskellPackages.aeson_0_11_3_0                               aeson-0.11.3.0
haskellPackages.aeson_0_7_0_6                                aeson-0.7.0.6
haskellPackages.aeson                                        aeson-1.1.2.0
```
I guess my question would be, is it possible to relax the constraints for pandoc without any problem ? the gap in aeson versioning suggest it will be harder.

**Comment by jgm** [comment]
Oh, yes.  I hadn't realized it had been so long since a
release, since I suppose I compiled my own from the git
repo.  I can make a new release that supports pandoc 1.19.

**Comment by teto** [comment]
Any hackage update is picked up automatically by nixos so that would be great in fact.

**Comment by jgm** [comment]
I've released a new version.

+++ Matthieu Coudron [Sep 19 17 23:03 ]:

**Comment by teto** [comment]
Thanks a lot. I still have some problems but it's on the nixpkgs side so I close this. Thanks a lot !
